DO_API_KEY: "{{ lookup('env', 'DO_API_TOKEN') }}"
DO_REGION_ID: sgp1
DO_SIZE_ID: "s-1vcpu-1gb"
DO_IMAGE_ID: "ubuntu-18-04-x64"

# Version
KUBE_VERSION: "1.15"
DOCKER_VERSION: "18.06"


# 
SUDO_USER: ubuntu

# nodes
K8S_NODES:
  - {"name": "master01", "tags": ["master"]}
  - {"name": "worker01", "tags": ["worker"]}
