---

- hosts: all
  gather_facts: true
  become: true
  roles:
    - common

- hosts: master
  gather_facts: true
  become: true
  roles:
    - master

- hosts: worker
  gather_facts: true
  become: true
  roles:
    - worker
